language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.0
      env: SYMFONY_VERSION="^3.4"
    - php: 7.1
      env: SYMFONY_VERSION="^4.0"

before_script:
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi
  - ./src/BeSimple/SoapClient/Tests/bin/phpwebserver.sh
  - ./src/BeSimple/SoapClient/Tests/bin/axis.sh

install: COMPOSER_MEMORY_LIMIT="2G" composer update $COMPOSER_FLAGS --prefer-dist

script:
  - ./vendor/bin/phpunit
